// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwqxauloakvcruxerpdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3cXhhdWxvYWt2Y3J1eGVycGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjI4MjcsImV4cCI6MjA3NDEzODgyN30.ugZ7x4mysX-RzsDyFq7-lteLcj3ohiUo8cfpWwr3rNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});